language: node_js
node_js:
  - "6.5"

addons:
  postgresql: "9.4"

services:
  - postgresql

notifications:
  email:
    on_success: never

before_script:
  - psql -c 'create database unhypem;' -U postgres